### ISSUE TITLE
"The file could not be uploaded."

### ISSUE THREAD

**Issue by mxdvl** [mzur/kirby-uniform#164] opened 2018-12-13 09:02 UTC
I’m trying to upload files, but I get an error when trying to upload a file.

Here’s the controller:

```
use Uniform\Form;

return function ($site, $pages, $page)
{
    $form = new Form([
        'email' => [
            'rules' => ['required', 'email'],
            'message' => 'Please enter a valid email address',
        ],
        'message' => [
            'rules' => ['required'],
            'message' => 'Please enter a message',
        ],

        'subject' => [
            'rules' => ['required'],
            'message' => 'Please enter a subject',
        ],
        'filefield' => [
            'rules' => [
                'required',
                'file',
                'mime' => ['application/pdf'],
                'filesize' => 10000,
            ],
            'message' => [
                'Please choose a file.',
                'Please choose a file.',
                'Please choose a PDF.',
                'Please choose a file that is smaller than 10 MB.',
            ],
        ],
        'filecv' => [
            'rules' => [
                'file',
                'mime' => ['application/pdf'],
                'filesize' => 1000,
            ],
            'message' => [
                'Please choose a file.',
                'Please choose a file.',
                'Please choose a PDF.',
                'Please choose a CV that is smaller than 1 MB.',
            ],
        ],
    ]);

    if (r::is('POST')) {
        $form->uploadAction(['fields' => [
            'filefield' => [
                'target' => kirby()->roots()->index().'/uploads/',
                'prefix' => date("ymd-pf-"),
            ],
            'filecv' => [
                'target' => kirby()->roots()->index().'/uploads/',
                'prefix' => date("ymd-cv-"),
            ],
        ]])->emailAction([
            'to' => 'info@example.com',
            'from' => 'info@example.com',
            'replyTo' => get('email'),
            'subject' => '[Webform: Jobs] {subject}',
           
        ])->logAction([
            'file' => kirby()->roots()->site().'/contact-form.log'
        ]);;
    }

    return compact('form');
};
```

The uploads folder permissions are 744. The upload used to work a couple of months ago. I’m at a loss as to what could be causing the issue.

**Comment by mzur** [comment] 2018-12-15 10:57
This error occurs if `move_uploaded_file` cannot be executed ([here](https://github.com/mzur/kirby-uniform/blob/59424aed71c50370676ff56cab9d25b1af17167d/src/Actions/UploadAction.php#L115)). You should get a PHP warning message in this case. Please check your PHP (error) log for any warning messages.

**Comment by mzur** [comment] 2018-12-15 14:37
Duplicate of #142 
Feel free to continue the discussion there. I'm open for pull requests to improve this behavior :wink:

**Closed by mzur** 2018-12-15 14:37 UTC
